# Site settings
title: A blog of a machine learning engineer
url: "https://omar178.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Omar Ayman
user_description: Machine learning engineer and life-long learner
user_title: Machine learning engineer and life-long learner
email: omaraymanmar@gmail.com
twitter_username: OmarAymanOmarTa
github_username:  omar178
linkedin_username: omar-ayman-6498529b
disqus_username: Omar Ayman
name: Omar Ayman
# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

baseurl: ""

# Your disqus shortname, entering this will enable commenting on posts
disqus: Omar Ayman

avatar: https://avatars1.githubusercontent.com/u/31745935?s=400&u=5bc0b879a43e63687e69f9b5c42949b4719bdef3&v=4
# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
